<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P5-H80MX52" ignored="0" name="RetryMultipleFailedTestCases" tests="8" failures="2" timestamp="2019-11-19T16:22:35 IST" time="0.181" errors="0">
  <testcase name="method1" time="0.028" classname="com.test.RetryLogic">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.005" classname="com.test.RetryLogic">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.002" classname="com.test.RetryLogic">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase name="method1" time="0.002" classname="com.test.RetryLogic">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.test.RetryLogic.method1(RetryLogic.java:10)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase name="method2" time="0.002" classname="com.test.RetryLogic">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.002" classname="com.test.RetryLogic">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.002" classname="com.test.RetryLogic">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase name="method2" time="0.003" classname="com.test.RetryLogic">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.test.RetryLogic.method2(RetryLogic.java:15)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
</testsuite> <!-- RetryMultipleFailedTestCases -->
